# this config file is watched by mission_executor
# so you can change it without having to re-launch
#
# Example:
# ```
# [<auv_name>]
# tam = [
#    [ x, y, z, roll, pitch, yaw ]
#    ... a row for each thrustor
# ]
# [<auv_name>.<bridge_name_1>]
# kp = [ x, y, z, roll, pitch, yaw ]
# ki = [ x, y, z, roll, pitch, yaw ]
# kd = [ x, y, z, roll, pitch, yaw ]
# 
# [<auv_name>.<bridge_name_2>]
# kp = [ x, y, z, roll, pitch, yaw ]
# ki = [ x, y, z, roll, pitch, yaw ]
# kd = [ x, y, z, roll, pitch, yaw ]
# ```

[hydrus]
tam = [
  [ 0.0,  1.0,  0.0,  0.0,  0.0,  1.0],
  [ 0.0,  1.0,  0.0,  0.0,  0.0, -1.0],
  [ 0.0, -1.0,  0.0,  0.0,  0.0, -1.0],
  [ 0.0, -1.0,  0.0,  0.0,  0.0,  1.0],
  [ 0.0,  0.0, -1.0, -1.0,  1.0,  0.0],
  [ 0.0,  0.0, -1.0, -1.0, -1.0,  0.0],
  [ 0.0,  0.0, -1.0,  1.0,  1.0,  0.0],
  [ 0.0,  0.0, -1.0,  1.0, -1.0,  0.0],
]

[hydrus.pid.stonefish]
kp = [1.0, 1.0, 2.0, -2.0, 2.0, 2.0]
ki = [0.0, 0.0, 0.0, 0.0, 3.3, 2.0]
kd = [0.1, 0.1, 0.0, 4.1, 3.1, 2.0]


[proteus]
tam = [
  [ 0.0,  1.0,  0.0,  0.0,  0.0,  1.0],
  [ 0.0,  1.0,  0.0,  0.0,  0.0, -1.0],
  [ 0.0,  0.0, -1.0,  1.0,  1.0,  0.0],
  [ 0.0,  0.0, -1.0,  1.0, -1.0,  0.0],
  [ 0.0,  0.0, -1.0, -1.0,  1.0,  0.0],
  [ 0.0,  0.0, -1.0, -1.0, -1.0,  0.0],
]

[proteus.pid.stonefish]
kp = [1.0, 1.0, 2.2, 2.4, 2.4, 2.0]
ki = [0.0, 0.0, 0.05, 0.05, 0.05, 0.0]
kd = [0.1, 0.1, 0.4, 0.2, 0.2, 2.0]

[proteus.pid.hardware]
kp = [1.0, 1.0, 2.2, 2.4, 2.4, 2.0]
ki = [0.0, 0.0, 0.05, 0.05, 0.05, 0.0]
kd = [0.1, 0.1, 0.4, 0.2, 0.2, 2.0]

[bluerov2]
# NOT A TRUE TAM FILE [ITS JUST A PLACEHOLDER]
tam = [
  [ 1.0, -1.0,  0.0,  1.0,  1.0, -1.0],
  [ 1.0,  1.0,  0.0, -1.0,  1.0,  1.0],
  [-1.0, -1.0,  0.0,  1.0, -1.0,  1.0],
  [-1.0,  1.0,  0.0, -1.0, -1.0, -1.0],
  [ 0.0,  0.0,  1.0,  1.0, -1.0,  1.0],
  [ 0.0,  0.0,  1.0, -1.0, -1.0, -1.0],
  [ 0.0,  0.0,  1.0,  1.0,  1.0,  1.0],
  [ 0.0,  0.0,  1.0, -1.0,  1.0, -1.0],
]

[bluerov2.pid.stonefish]
kp = [1.0, 1.0, 2.2, 2.4, 2.4, 2.0]
ki = [1.0, 1.0, 0.05, 0.05, 0.05, 1.0]
kd = [1.1, 0.1, 0.4, 0.2, 0.2, 2.0]
