vectornav:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baud: 115200
    reconnect_ms: 500
    AsyncDataOutputType: 0
    AsyncDataOutputFrequency: 20
    syncInMode: 3
    syncInEdge: 0
    syncInSkipFactor: 0
    syncOutMode: 0
    syncOutPolarity: 0
    syncOutSkipFactor: 0
    syncOutPulseWidth_ns: 100000000
    serialCount: 0
    serialStatus: 0
    spiCount: 0
    spiStatus: 0
    serialChecksum: 1
    spiChecksum: 0
    errorMode: 1
    BO1:
      asyncMode: 3
      rateDivisor: 40
      commonField: 32767
      timeField: 0
      imuField: 0
      gpsField: 0
      attitudeField: 0
      insField: 0
      gps2Field: 0
    BO2:
      asyncMode: 0
      rateDivisor: 0
      commonField: 0
      timeField: 0
      imuField: 0
      gpsField: 0
      attitudeField: 0
      insField: 0
      gps2Field: 0
    BO3:
      asyncMode: 0
      rateDivisor: 0
      commonField: 0
      timeField: 0
      imuField: 0
      gpsField: 0
      attitudeField: 0
      insField: 0
      gps2Field: 0
    frame_id: "vn100_link"

vn_sensor_msgs:
  ros__parameters:
    use_enu: true
    orientation_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    angular_velocity_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    linear_acceleration_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    magnetic_covariance: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
